### ISSUE TITLE
If client is moved or kicked, plugin doesn't work

### ISSUE THREAD

**Issue by DatDraggy** [gTX31vsg/ts3-autofollow#1]
Bugs:
- [ ] When followed client is moved, following client doesn't follow. 
- [ ] When followed client is kicked from channel, following client doesn't follow. 
- [ ] When following client is moved, doesn't rejoin to follow followed client. ts3plugin_onClientMoveMovedEvent
- [ ] When following client is kicked from channel, doesn't rejoin to follow followed client. ts3plugin_onClientKickFromChannelEvent

When I have time I'll do it myself but I don't know when and if that's going to happen.
I'd like to use your plugin because it's useful, but it's not completly usable yet.

**Comment by nko-sh** [comment]
Thanks for mentioning, it should be fixed now with f643fe0850da919f5932412e06863da44a2979a1
